### ISSUE TITLE
legend "text box" too large

### ISSUE THREAD

**Issue by telsin** [20c/graphsrv#11]
The translucent black box the legends are in extends to far to the right and makes it harder to read part of the graphs. Should be limited to the width of the text.

Would also be nice to have an option to make it transparent instead of translucent.

**Comment by vegu** [comment]
going to underlay a subtle textshadow instead and get rid of the box shape entirely

![screen shot 2017-03-30 at 11 56 20](https://cloud.githubusercontent.com/assets/143124/24496125/11df0dc8-1540-11e7-9a6b-231d7f7e1e87.png)
