### ISSUE TITLE
"No Data Feed" issues cause graphs to pause, offsetting time. Should be gaps in graph instead.

### ISSUE THREAD

**Issue by telsin** [20c/graphsrv#20]
This is particularly obvious with multiple graphs running. A graph which looses it's data feed gets off in time from the others, and presents misleading data when it's feed resumes. Graph should gap instead, and continue scrolling even though there is no data feed. All graphs should be sync'd in time, more or less.

The "No Data Feed" indicator is really nice though!

**Comment by vegu** [comment]
fixed with #25 - it can be made prettier still as it will just connect the plot through the gap when it comes back, but there is a gap now.
