### ISSUE TITLE
graphserv does not default to "index" layout if any other layout name is present

### ISSUE THREAD

**Issue by telsin** [20c/graphsrv#22]
and I wish it would, it makes it hard to test custom layouts without breaking your base display page.

**Comment by vegu** [comment]
That sounds like a bug, can you post your layout.yaml file.

**Comment by telsin** [comment]
layouts:

  ## INDEX #####################################################################

  index:
    type: index
    grid: 3x3
    graph:
      config: multitarget
      fit: 'yes'
      targets: all

  ## DETAIL ####################################################################
  
  detail:
    type: custom
    layout:
    # row 1
    - cols:
      # col 1, render a graph
      - graph:
  
          config: multitarget
          
          # fit to column
          fit: 'yes'
          
          # render all targets to this graph
          targets: all
  
          # custom graph id
          id: multitarget-1
        width: 12 
      height: 75
  
    # row 2
    - cols:
      - graph:
          fit: 'yes'
          config: smokestack
          targets: all 
          id: smokestack-1
        width: 4
      - graph:
          fit: 'yes'
          config: smokestack
          targets: all
          id: smokestack-2
        width: 4
      - graph:
          fit: 'yes'
          config: smokestack
          targets: all
          id: smokestack-3
        width: 4
      height: 25
  
#  atest:
#    type: custom
#    layout:
#    - cols:
#      - graph:
#          config: multitarget
#          fit: 'yes'
#          targets: latency.transit
#          id: latency.transit 
#        width: 4
#      - graph:
#          config: multitarget
#          fit: 'yes'
#          targets: all
#          id: latency.public_dns
#        width: 4
#      - graph:
#          config: multitarget
#          fit: 'yes'
#          targets: all
#          id: latency.comcast_targets
#        width: 4
#      height: 34
#    - cols:
#      - graph:
#          config: multitarget
#          fit: 'yes'
#          targets: all
#          id: latency.peers
#        width: 4
#      - graph:
#          config: multitarget
#          fit: 'yes'
#          targets: all
#          id: from_comcast.public_dns
#        width: 4
#      - graph:
#          config: multitarget
#          fit: 'yes'
#          targets: all
#          id: from_comcast.IL
#        width: 4
#      height: 33
#    - cols:
#      - graph:
#          config: multitarget
#          fit: 'yes'
#          targets: all
#          id: latency.transit
#        width: 4
#      - graph:
#          config: multitarget
#          fit: 'yes'
#          targets: all
#          id: from_charter.public_dns
#        width: 4
#      - graph:
#          config: multitarget
#          fit: 'yes'
#          targets: all
#          id: from_charter.WI
#        width: 4
#      height: 33
#

**Comment by telsin** [comment]
Let's try that again... Was simpler when I discovered this, tried naming my added layout atest or test to try different possible sort orders. Uncomment that layout and it will be presented if you don't specify anything. Comment it and you get the default index again.

[layout.yaml.txt](https://github.com/20c/graphsrv/files/1359785/layout.yaml.txt)

**Comment by vegu** [comment]
Curious that it doesnt do it with the other custom layout already in there, i'll have a look

**Comment by telsin** [comment]
That other custom layout is part of the default config out of the box (default page for a "zoomed in" graph), I'd guess it has special meaning in code somewhere.

**Comment by vegu** [comment]
Seems to have something to do with the name of the layout "test" and "atest" for example result in the issue, "testlayout" on the other hand doesn't.
