### ISSUE TITLE
legend sorting

### ISSUE THREAD

**Issue by telsin** [20c/graphsrv#7]
Graphsrv appears to randomly sort entries in its legend, resulting in out of order entries for me. For example, my config file has [A1, A2, B1, B2, C1, C2, D1, D2] and the legend is sorted [B1, B2, C1, C2, D2, A2, D1, A1]

Would prefer it to sort in order of entries, or alphabetically, or have a value to indicate the sort order for legend.

**Comment by vegu** [comment]
going to do alphabetic sorting for now, can investigate more sophisticated solutions down the line if needed
